// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIpT08aszgsJPs-g7UUJ_5Sy6dUMdhGc8',
    appId: '1:821333894656:web:902e450031c134706edae5',
    messagingSenderId: '821333894656',
    projectId: 'chakri-chai',
    authDomain: 'chakri-chai.firebaseapp.com',
    storageBucket: 'chakri-chai.appspot.com',
    measurementId: 'G-WGFNM8DCQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzCwZ-PMjxvkczhq0uu0lgqqIPs61uNVo',
    appId: '1:821333894656:android:819ac6b577bb92336edae5',
    messagingSenderId: '821333894656',
    projectId: 'chakri-chai',
    storageBucket: 'chakri-chai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9qSS9hlDHSjHBgPeqeHD49MRRAkjDT8Q',
    appId: '1:821333894656:ios:f657048657ff286a6edae5',
    messagingSenderId: '821333894656',
    projectId: 'chakri-chai',
    storageBucket: 'chakri-chai.appspot.com',
    iosClientId: '821333894656-c9j6uip7893612jsv2nc9dg4tkbo0srn.apps.googleusercontent.com',
    iosBundleId: 'com.example.chakriChai',
  );
}
